### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by meshula** [lji-ilm/openexr-notes#1]
Per our conversation yesterday, a section on Architecture might be good. 

- diagram of IlmImf, and OpenEXR core
   - metadata used for informational purposes (on-set forensics)
   - metadata without which an image can't be interpreted
   - image layer
   - codec
   - input/output

- analysis of whether codec can be factored clear of i/o
  - allow IlmImf to use Core for codec
  - allow researchers to create new codecs without having to also deal with I/O
 
- analysis of whether i/o can be factored clear
  - allow IlmImf to use Core for I/O
  - allow researchers to create new codecs to experiment with features such as streaming

- analysis of using factored metadata, code, i/o to embed OpenEXR into other container formats such as ImageJ

**Comment by lji-ilm** [comment]
Yes, I'm particularly interested in further study these two points, in the bigger context of "separating IO with Codec" :
- allow IlmImf to use Core for codec
- allow IlmImf to use Core for I/O

I'm not clear where is this  IlmImf component -- where is it exactly on the open source repo. I understand currently things probably all mashed together in the `lib/OpenEXR` folder, but I couldn't even identify files that looks like this.

My guess is that the current situation is this:
1. `lib/OpenEXR` is a full C++ stack of exr. There is a part of this corresponding to the `Ilmlmf` thing you're talking about, but **I'm not sure which part**? This part uses the other stuff inside the C++ stack to complete IO+compression etc.
2. `lib/OpenEXRCore` is a self-contained C stack of exr, it doesn't depends on `Iex` nor `IlmThread`, but the `lib/OpenEXR` doesn't use anything in the C stack either.

I'm in general in favor of develop further the Core lib, and agree with you about the separation of IO <-> Codec.

**Comment by meshula** [comment]
OpenEXR used to be several libraries called IlmBase, IlmImf, IlmThread, etc. Now it's all blobbed into OpenEXR. Pretend I wrote "Imf" and I hope it is no longer confusing.

**Comment by lji-ilm** [comment]
IlmThread is still separate, but yeah I'm not sure how IlmBase and Ilmlmf maps to the current code base. Maybe IlmBase is Imath?

However I think the first step in the Open Source side is really to enhance the usability of the Core/C lib, to work on the C lib rather than to attempt linking the C++ API layer onto it. I tried to use the C API for a little bit but as we know it is far far from straightforward. 

On the other hand, it's a good timing for we to act NOW to clean up the Core/C lib, this one still have a somewhat limited audience and some API-breaking updates won't hurts as much as changing the C++ lib's API, i suppose. This timing won't last forever, tho.

**Comment by meshula** [comment]
The mapping of the old libraries is not important, the history is in github if you are really interested.

I would suggest that the openexr-c wrapping of OpenExrCore here https://github.com/PixarAnimationStudios/OpenUSD/tree/release/pxr/imaging/hio/OpenEXR might be a good starting point. It doesn't exercise all of core, but it does demonstrate reading and writing, fetching attributes, and other interesting operations.

**Comment by lji-ilm** [comment]
Yes, let me start from there.
Let's assume down the road we want to make a API-breaking change to Core, do you think there are other significant audiences of ExrCore other than your work in USD?

**Comment by lji-ilm** [comment]
After reading the code a bit I think nanoexr might just be added to the openexr core.

maybe minus that Gaussian resample part, but a curated turn-key "read metadata" and a turn-key "read image into RAM" is obviously needed. Same for the writing side. If we want to continue with the "style" of the current Core library (so people can be free to build more optimized/parallelized) high level APIs on top, these nano C method can be put into an utility folder instead of in the same folder with some tightly vetted, thread-safe C routines. (Although I think the current Core C routines are probably not that tightly vetted.)

The flow of your `nanoexr_read_exr` reminds me of the classical "The first tutorial of learning Direct X - how to put up a triangle on your screen!" https://github.com/microsoft/DirectX-Graphics-Samples/blob/master/Samples/Desktop/D3D12HelloWorld/src/HelloTriangle/D3D12HelloTriangle.cpp

It is terribly confusing for any student aspiring to learn computer graphics I ever taught.

**Comment by meshula** [comment]
The Gaussian resample is required by USD/Hydra but shouldn't be part of core.

ExrCore is not by any public projects I know of, except for OpenImageIO, and I think one of the open source renderers, but I can't find it at the moment.

It's not surprising that the code reminds you of HelloTriangle, due to (1) the Core coding model, and (2) it was my HelloOpenEXRCore, and a lot of trial and error was involved. Probably a prettier implementation is possible, but it's not immediately obvious how to clean it more.

**Comment by lji-ilm** [comment]
I was trying to say the issue for clarity is more with the C-API, not in the way your nano reader was written. 
The HelloTriagle example was obviously curated to be as easy to read as possible; but the underlying DirectX design dictated it must run into a terribly complicated structure.
But I can see the C-API is targeting to become atomic building blocks of both simple and high performance exr pipelines so it is designed in that way, but some slightly clean up and much more documentation would be helpful.

**Comment by lji-ilm** [comment]
Here is a comparison and the overlapping points of the wish list at the top of this thread v.s. https://wiki.aswf.io/display/OEXR/OpenEXR+Project+Ideas

1. **Better Compression of raw half image streams**. 
2. **Better metadata mgmt**. This could be divided into a few aspects, they're related.
    a. Performance. Permit fast metadata load without loading the image, sorted metadata API, etc
    b. Segregation of semantics. Divided between image-intrinsic metadata v.s production metadata. Joseph's camdkit proposal, etc.
    c. Spectral (https://inria.hal.science/hal-03252797), color space (Carol Payne) etc.
    d. A Part Type that is only Metadata for very heavy metadata etc (an essay of on-set notes?? audio?)
3. **Improved C (Core) implementation**. This has a few aspects too:
    a. Separate file structure & IO (tile, scanline) v.s. codec (compression, lossless v.s. slightly-lossy) into orthogonal parts of the lib.
    b. Let the C++ ilm implementation to use Core for both file IO and codec.
    c. Better documentation and usage example for Core. Thanks for the head start this with the hioexr project.
    d. Rebuild the python binding, possibly also directly on top of Core.
4. **Benchmark** and housekeeping
    a. Get rid of boost:python (see 3.d)
    b. Curate a larger "official" open-source exemplar exr image dataset. 
    c. Establish performance metrics (speed, compression rate, fast preview playback rate, etc). this depends on 4.b

Amongst the above, I might not be able to cover No.2 with a research project. I recognize it is an important topic but there will be difficulty in try to get scientific money for a pipeline-oriented piece. The other could be put into a single coherent research pitch, i think.

**Comment by lji-ilm** [comment]
I'm getting progress in making a research pitch, will have something to report back soon @meshula 

Closing this thread -- thanks for the feedback!
